name = "datasaaslab-blog"
compatibility_date = "2026-02-17"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "SESSION"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_KV_PREVIEW_NAMESPACE_ID"
